== Introduction

The RISC-V vector C intrinsics provides users interfaces in the C language level to directly leverage the RISC-V "V" extension ^0^ (also abbreviated as "RVV"), with help from the compiler to handle instruction scheduling and register allocation. The RVV C intrinsics also aims to free users from responsibility to maintain the correct configuration setting ^18^ for the vector instruction executions.

This document uses the term "v-spec" to indicate the RISC-V "V" extension specification ^0^. This document also uses the term "RVV" as an abbreviation for the RISC-V "V" extension.

== Test macro

The `__riscv_v_intrinsic` macro is macro to test the compiler's support for the RISC-V "V" extension C API.

The value of the test macro is defined as its version, which is computed by the following formula. The formula is identical to what is defined under the RISC-V C API specification ^1^ .

```
<MAJOR_VERSION> * 1,000,000 + <MINOR_VERSION> * 1,000 + <REVISION_VERSION>
```

For example, the v1.0 version should define the macro with value `1000000`.

== Header file inclusion

To leverage the intrinsics in the compiler, the header `<riscv_vector.h>` needs to be included. We suggest the inclusion to be guarded with the test macro.

```c
#ifdef __riscv_v_intrinsic
#include <riscv_vector.h>
#endif /* __riscv_v_intrinsic */
```

== Availability

With `<riscv_vector.h>` included, availability of intrinsic variants depends on the required architecture of their corresponding vector instruction. The supported architecture is passed into the compiler using the `-march` option ^2,3^.

The standard vector extensions ^19^ provides a set of smaller extensions for embedded use. Please checkout the `Zve` extensions ^20^ for the varying degree of support.

For example, RVV type `vint64m1_t` and `__riscv_vle64_v_i64m1` is not available under architecture `rv64gc_zve32x`.

[[control-of-vector-programming-model]]
== Control of the vector extension programming model

The intrinsics allow users to control fields in `vtype`, and also rounding modes for fixed-point (`vxrm`) and floating-point (`frm`) vector computations.

In this section, we cover how the intrinsics embed the control of `vtype` fields in the function names. Please see <<naming-scheme>> for the rules described in this section.

=== Control of `eew`, `emul`

The RISC-V vector intrinsics data types are strongly-typed, and hence so are the intrinsics taking these types as parameters. The vector intrinsics encode the EEW (effective-element-width) ^17^ and EMUL (effective LMUL) ^17^ of the destination vector register into the suffix of the function name. Users can expect the results of the vector instruction intrinsics are computed under the specified EEW and EMUL.

To see the full list of data types for the intrinsics, please see <<type-system>>.

In the following example, the intrinsic will produce the semantic of a `vadd.vv` instruction, with source vector operands of `EEW=32` and `EMUL=1`, which can be observed through provided RVV data type; and produce results to destination vector operands with `EEW=32` and `EMUL=1`.

```
vint32m1_t __riscv_vadd_vv_i32m1 (vint32m1_t op1, vint32m1_t op2, size_t vl);
```

In the following example, the intrinsic will produce the semantic of a `vadd.vv` instruction, with source vector operands of `EEW=16` and `EMUL=1/2`, which can be observed through provided RVV data type; and produce results to destination vector operands with `EEW=32` and `EMUL=1`.

```
vint32m1_t __riscv_vwadd_vv_i32m1 (vint16mf2_t op1, vint16mf2_t op2, size_t vl);
```

=== Control of `vl`

Direct control of `vl` (vector length register) ^11^  is not exposed at the C language level. The RVV C intrinsics provide intrinsics with a `vl` operand to indicate the active vector length valid during intrinsic execution. The compiler is responsible to set the correct value to `vl` given the informed active vector length.

NOTE: Intrinsics for instructions that behave the same with different `vl` settings (e.g. `vmv.s.x`) do not have a `vl` operand.

NOTE: Intrinsics will at most operate on `VLMAX` ^5^ elements.

[[control-of-masked]]
=== Control of `vm`

Instructions that are available for masking ^7^ have masked variant intrinsics.

The RVV intrinsics fuse the control of vector masking (`vm`) together with the control for the policy behavior (`vta`, `vma`) in the same suffix. Please checkout <<control-of-policy>> and <<policy-and-masked-naming-scheme>> for the exact suffix that specifies a masked/unmasked vector operation along with its policy behavior.

[[control-of-policy]]
=== Control of `vta`, `vma`

The behavior of destination tail elements and destination inactive masked-off elements is controled by the `vta` and `vma` bits ^6^.

Given the general assumption that target audience of the RVV intrinsics are high performance cores, and an "undisturbed" policy will generally slow down an out-of-order core, the intrinsics have a default policy scheme of tail-agnostic and mask-agnostic (that is, `vta=1` and `vma=1`).

The RVV intrinsics fuse the control of vector masking (`vm`) together wuth the control for the policy behavior (`vta`, `vma`) in the same suffix. Please checkout <<control-of-masked>> and <<policy-and-masked-naming-scheme>> for the exact suffix that specifies a masked/unmasked vector operation along with its policy behavior.

=== Control of `vxrm`

For the fixed-point intrinsics, representing the fixed-point arithmetic instructions ^21^, the `vxrm` operand of the intrinsics indicates the rounding mode (`vxrm`) ^8^ control.

The `vxrm` operand is required to be an constant integer expression. The compiler should implement the following `enum` that maps to the defined rounding mode values under v-spec Table 4 ^8^.

```c
enum __RISCV_VXRM {
  __RISCV_VXRM_RNU = 0,
  __RISCV_VXRM_RNE = 1,
  __RISCV_VXRM_RDN = 2,
  __RISCV_VXRM_ROD = 3,
};
```

NOTE: Rounding mode does not affect the computations of `vsadd`, `vsaddu`, `vssub`, and `vssubu`, therefore the intrinsics of these instructions do not have the `vxrm` parameter.

NOTE: The RISC-V psABI ^9^ states that `vxrm` is not preserved across calls. Optimization for reducing the number of redundant writes to `vxrm` is a compiler and system specific issue.

NOTE: Control to the vector fixed-point saturation flag (`vxsat`) ^22^ is not yet covered in the RVV C intrinsics v1.0. We plan to support them in follow-up versions in a compatible way with existing intrinsics in v1.0.

[[control-of-frm]]
=== Control of `frm`

For the floating-point intrinsics, representing the floating-point arithmetic instructions ^23^, the intrinsics have two variants, called the implicit-`frm` and the explicit-`frm` intrinsics.

NOTE: Control to the floating-point accrued exceptions flag fields (`fflag`) ^10^ is not yet covered in the RVV C intrinsics v1.0. We plan to support them in follow-up versions in a compatible way with existing intrinsics in v1.0.

==== Implicit-`frm` intrinsics

The implicit-`frm` intrinsics behave like any C-language floating-point expressions, using the default rounding mode when `FENV_ACCESS` is off, and using the `fenv` dynamic rounding mode when `FENV_ACCESS` is on.

NOTE: Both GNU and LLVM compilers generate scalar floating-point instructions using dynamic rounding mode, relying on the kernel initialization to set `frm` to `RNE` (specified as "roundTiesToEven" in IEEE-754 (a.k.a. IEC 60559)).

NOTE: The implicit-`frm` intrinsics are intended to be used regardless of `FENV_ACCESS`. They are provided when `FENV_ACCESS` is on for the (few) programmers who are already using fenv; and they are provided when `FENV_ACCESS` is off for the (vast majority of) programmers who prefer the default rounding mode.

[[explicit-frm]]
==== Explicit-`frm` intrinsics

The explicit-`frm` intrinsics contain the `frm` operand which indicates the rounding mode (`frm`) ^10^ control. The floating-point intrinsics with the `frm` operand are followed by an `_rm` suffix in the function name.

The `frm` operand is required to be an integer constant expression. The compiler should implement the following enum that maps to the defined rounding mode values under RISC-V ISA Manual Table 8.1 ^9^.

```c
enum __RISCV_FRM {
  __RISCV_FRM_RNE = 0,
  __RISCV_FRM_RTZ = 1,
  __RISCV_FRM_RDN = 2,
  __RISCV_FRM_RUP = 3,
  __RISCV_FRM_RMM = 4,
};
```

NOTE: The explicit-`frm` intrinsics are intended to be used when `FENV_ACCESS` is off, to enable more aggressive optimization while still providing the programmer with control over the rounding mode. Using explicit-`frm` intrinsics when `FENV_ACCESS` is on will still work correctly, but is expected to lead to extra saving/restoring of `frm`, that could be avoided by using `fenv` functionality and implicit-`frm` intrinsics.

[[naming-scheme]]
== Naming scheme

The naming scheme of the intrinsics expresses the users' control of fields in `vtype`, `vl`, and rounding modes for the fixed-point and the floating-point vector computations. For details of these CSR controls, please see <<control-of-vector-programming-mode>>.

As mentioned in <<control-of-masked>> and <<control-of-policy>>, the intrinsics fuses the control to `vm`, `vta` and `vma` into the same suffix. <<policy-and-masked-naming-scheme>> enumerates the exact suffixes. You may find where are these suffixes appended in <<explicit-naming-scheme>>.

The RVV intrinsics can be split into two major types, called "explicit (non-overloaded) intrinsics" and "implicit (overloaded) intrinsics".

The explicit (non-overloaded) intrinsics embed the control described under <<control-of-vector-programming-model>> in the function name. This scheme gives intrinsic codebase more readability given the execution states be explicitly specified in the code.

The implicit (overloaded) intrinsics, on the contrary, hide the explicit specifications for `vtype` control. The implicit (overloaded) intrinsics aim to provide a generic interface to let users put values of different EEW ^17^ and EMUL ^17^ as the input operand.

This section covers the general naming rule of the two types of intrinsics accordingly. Then, this section also enumerates the exceptions and the rationale behind them in <<explicit-exception-naming>> and <<implicit-exception-naming>>.

[[policy-and-masked-naming-scheme]]
=== Policy and masked naming scheme

With the default policy scheme mentioned under <<control-of-policy>>, each intrinsic provides corresponding variants for their available control of `vm`, `vta` and `vma`. The following list enumerates the control their corresponding suffix.

* No suffix: Represents an unmasked (`vm=1`) vector operation with tail-agnostic (`vta=1`)
* `_tu` suffix: Represents an unmasked (`vm=1`) vector operation with tail-undisturbed (`vta=0`) policy
* `_m` suffix: Represents a masked (`vm=0`) vector operation with tail-agnostic (`vta=1`), mask-agnostic (`vma=1`) policy
* `_tum` suffix: Represents a masked (`vm=0`) vector operation with tail-undisturbed (`vta=0`), mask-agnostic (`vma=1`) policy
* `_mu` suffix: Represents a masked (`vm=0`) vector operation with tail-agnostic (`vta=1`), mask-undisturbed (`vma=0`) policy
* `_tumu` suffix: Represents a masked (`vm=0`) vector operation with tail-undisturbed (`vta=0`), mask-undisturbed (`vma=0`) policy

Using `vadd` with EEW=32 and EMUL=1 as an example, the variants are:

```c
// vm=1, vta=1
vint32m1_t __riscv_vadd_vv_i32m1(vint32m1_t op1, vint32m1_t op2, size_t vl);
// vm=1, vta=0
vint32m1_t __riscv_vadd_vv_i32m1_tu(vint32m1_t maskedoff, vint32m1_t op1,
                                    vint32m1_t op2, size_t vl);
// vm=0, vta=1, vma=1
vint32m1_t __riscv_vadd_vv_i32m1_m(vbool32_t mask, vint32m1_t op1,
                                   vint32m1_t op2, size_t vl);
// vm=0, vta=0, vma=1
vint32m1_t __riscv_vadd_vv_i32m1_tum(vbool32_t mask, vint32m1_t maskedoff,
                                     vint32m1_t op1, vint32m1_t op2, size_t vl);
// vm=0, vta=1, vma=0
vint32m1_t __riscv_vadd_vv_i32m1_mu(vbool32_t mask, vint32m1_t maskedoff,
                                    vint32m1_t op1, vint32m1_t op2, size_t vl);
// vm=0, vta=0, vma=0
vint32m1_t __riscv_vadd_vv_i32m1_tumu(vbool32_t mask, vint32m1_t maskedoff,
                                      vint32m1_t op1, vint32m1_t op2,
                                      size_t vl);
```

NOTE: When policy is set to "agnostic", there is no guarantee of what will be in the tail/masked-off elements. Under this policy users should not assume the values within to be deterministic.

NOTE: Pseudo intrinsics mentioned under <<pseudo-intrinsics>> do not map to real vector intsructions. Therefore these intrinsics are not affected by the policy setting, nor do they have intrinsic variants of the suffixes listed above.

[[explicit-naming-scheme]]
=== Explicit (Non-overloaded) naming scheme

In general, the intrinsics are encoded as the following. The intrinsics under this naming scheme are the "non-overloaded intrinsics", which in parallel we have the "overloaded intrinsics" defined under <<implicit-naming-scheme>>.

The naming rules is the following.

```
__riscv_{V_INSTRUCTION_MNEMONIC}_{OPERAND_MNEMONIC}_{RETURN_TYPE}_{ROUND_MODE}_{POLICY}{(...)
```

* `OPERAND_MNEMONIC` are like `vv`, `vx`, `vs`, `vvm`, `vxm`
* `RETURN_TYPE` depends on whether the return type of the vector instruction is a mask register...
** For intrinsics that represents instructions with a non-mask destination register:
*** `EEW` is one of `i8 | i16 | i32 | i64 | u8 | u16 | u32 | u64 | f16 | f32 | f64`.
*** `EMUL` is one of `m1 | m2 | m4 | m8 | mf2 | mf4 | mf8`.
*** <<type-system>> explains the limited enumeration of EEW, LEUL pair.
** For intrinsics that represent intrinsics with a mask destination register:
*** `RETURN_TYPE` is one of `b1 | b2 | b4 | b8 | b16 | b32 | b64`, which is derived from the ratio `EEW`/`EMUL`.
* `V_INSTRUCTION_MNEMONIC` are like `vadd`, `vfmacc`, `vsadd`.
* `ROUND_MODE` is the `_rm` suffix mentioned in <<explicit-frm>>. Other intrinsics do not have this suffix.
* `POLICY` are enumerated under <<policy-and-masked-naming-scheme>>.

The general naming scheme is not sufficient to express intrinsics. The exceptions are enumerated in the proceeding section <<explicit-exception-naming>>.

[[explicit-exception-naming]]
=== Exceptions in the explicit (non-overloaded) naming scheme

This section enumerates the exceptions in the explicit (non-overloaded) naming scheme.

==== Scalar move instructions

Only encoding the return type will cause naming collision for the permutation instruction intrinsics. The intrinsics encode the input vector type and the the output scalar type in the suffix.

```c
int8_t vmv_x_s_i8m1_i8 (vint8m1_t vs2, size_t vl);
int8_t vmv_x_s_i8m2_i8 (vint8m2_t vs2, size_t vl);
int8_t vmv_x_s_i8m4_i8 (vint8m4_t vs2, size_t vl);
int8_t vmv_x_s_i8m8_i8 (vint8m8_t vs2, size_t vl);
```

==== Reduction instructions

Only encoding the return type will cause naming collision for the reduction instruction intrinsics. The intrinsics encode the input vector type and the output vector type in the suffix.

```c
vint8m1_t vredsum_vs_i8m1_i8m1(vint8m1_t dest, vint8m1_t vs2, vint8m1_t vs1,
                               size_t vl);
vint8m1_t vredsum_vs_i8m2_i8m1(vint8m1_t dest, vint8m2_t vs2, vint8m1_t vs1,
                               size_t vl);
vint8m1_t vredsum_vs_i8m4_i8m1(vint8m1_t dest, vint8m4_t vs2, vint8m1_t vs1,
                               size_t vl);
vint8m1_t vredsum_vs_i8m8_i8m1(vint8m1_t dest, vint8m8_t vs2, vint8m1_t vs1,
                               size_t vl);
```

==== `vreinterpret`, `vlmul_trunc`/`vlmul_ext`, and `vset`/`vget`

Only encoding the return type will cause naming collision for these pseudo instructions. The intrinsics encode the input vector type before the return type in the suffix.

The following shows an example with `__riscv_vreinterpret_v` of `vint32m1_t` input vector type.

```c
vfloat32m1_t __riscv_vreinterpret_v_i32m1_f32m1 (vint32m1_t src);
vuint32m1_t __riscv_vreinterpret_v_i32m1_u32m1 (vint32m1_t src);
vint8m1_t __riscv_vreinterpret_v_i32m1_i8m1 (vint32m1_t src);
vint16m1_t __riscv_vreinterpret_v_i32m1_i16m1 (vint32m1_t src);
vint64m1_t __riscv_vreinterpret_v_i32m1_i64m1 (vint32m1_t src);
vbool64_t __riscv_vreinterpret_v_i32m1_b64 (vint32m1_t src);
vbool32_t __riscv_vreinterpret_v_i32m1_b32 (vint32m1_t src);
vbool16_t __riscv_vreinterpret_v_i32m1_b16 (vint32m1_t src);
vbool8_t __riscv_vreinterpret_v_i32m1_b8 (vint32m1_t src);
vbool4_t __riscv_vreinterpret_v_i32m1_b4 (vint32m1_t src);
```

[[implicit-naming-scheme]]
=== Implicit (Overloaded) naming scheme

The implicit (overloaded) interface aims to provide a generic interfaces taking values of different EEW and EMUL as the input. Therefore the implicit intrinsics hide the EEW and EMUL encoded in the function name. The `_rm` prefix for explicit-`frm` intrinsics (<<control-of-frm>>) is also hidden. The intrinsics under this scheme are the "overloaded intrinsics", which in parallel we have the "non-overloaded intrinsics" defined under <<explicit-naming-scheme>>.

Take the vector addition (`vadd`) instruction intrinsics as an example, stripping off the operand mnemonics and encoded EEW, EMUL information, the intrinsics API provides the following overloaded interfaces.

```c
vint32m1_t __riscv_vadd(vint32m1_t v0, vint32m1_t v1, size_t vl);
vint16m4_t __riscv_vadd(vint16m4_t v0, vint16m4_t v1, size_t vl);
```

Since the main intent is to let the users put different values of EEW and EMUL as input operand, the overloaded intrinsics do not hide the policy suffix. That is, suffix listed under <<control-of-policy>> is not hidden and is still encoded in the function name.

The masked variants with the default policy shares the same interface with the unmasked variants with the default policy. They do not have any trailing suffixes.

Take the vector floating-point add (`vfadd`) as an example, the intrinsics provides the following overloaded interfaces.

```c
vfloat32m1_t __riscv_vfadd(vbool32_t mask, vfloat32m1_t op1, vfloat32m1_t op2,
                           unsigned int frm, size_t vl);
vfloat16m4_t __riscv_vfadd(vbool4_t mask, vfloat16m4_t op1, vfloat16m4_t op2,
                           unsigned int frm, size_t vl);
vfloat32m1_t __riscv_vfadd_tu(vfloat32m1_t maskedoff, vfloat32m1_t op1,
                              vfloat32m1_t op2, size_t vl);
vfloat32m1_t __riscv_vfadd_tum(vbool32_t mask, vfloat32m1_t maskedoff,
                               vfloat32m1_t op1, vfloat32m1_t op2, size_t vl);
vfloat32m1_t __riscv_vfadd_tumu(vbool32_t mask, vfloat32m1_t maskedoff,
                                vfloat32m1_t op1, vfloat32m1_t op2, size_t vl);
vfloat32m1_t __riscv_vfadd_mu(vbool32_t mask, vfloat32m1_t maskedoff,
                              vfloat32m1_t op1, vfloat32m1_t op2, size_t vl);
vfloat32m1_t __riscv_vfadd_tu(vfloat32m1_t maskedoff, vfloat32m1_t op1,
                              vfloat32m1_t op2, unsigned int frm, size_t vl);
vfloat32m1_t __riscv_vfadd_tum(vbool32_t mask, vfloat32m1_t maskedoff,
                               vfloat32m1_t op1, vfloat32m1_t op2,
                               unsigned int frm, size_t vl);
vfloat32m1_t __riscv_vfadd_tumu(vbool32_t mask, vfloat32m1_t maskedoff,
                                vfloat32m1_t op1, vfloat32m1_t op2,
                                unsigned int frm, size_t vl);
vfloat32m1_t __riscv_vfadd_mu(vbool32_t mask, vfloat32m1_t maskedoff,
                              vfloat32m1_t op1, vfloat32m1_t op2,
                              unsigned int frm, size_t vl);
```

The naming scheme to prune everything except the instruction mnemonics is not available for all of the intrinsics. Please see <<implicit-exception-naming>> for overloaded intrinsics with irregular naming patterns.

Due to the limitation of the C language (without the aid of features like C++ templates), some intrinsics do not have an overloaded version. Therefore these intrinsics do not possess a simplified, EEW/EMUL-hidden interface. Please see <<unsupported-implicit-naming>> for more detail.

[[implicit-exception-naming]]
=== Exceptions in the implicit (overloaded) naming sheme

The following intrinsics have an irregular naming pattern.

==== Widening instructions

Widening intruction intrinsics (e.g. `vwadd`) have the same return type but different parameters. The operand mnemonics are encoded into their overloaded versions to help distinguish them.

```c
vint32m1_t __riscv_vwadd_vv (vint16mf2_t op1, vint16mf2_t op2, size_t vl);
vint32m1_t __riscv_vwadd_vx (vint16mf2_t op1, int16_t op2, size_t vl);
vint32m1_t __riscv_vwadd_wv (vint32m1_t op1, vint16mf2_t op2, size_t vl);
vint32m1_t __riscv_vwadd_wx (vint32m1_t op1, int16_t op2, size_t vl);
```

==== Type-convert instructions

Type-convert instruction intrinsics (e.g. `vfcvt.x.f`, `vfcvt.xu.f`, `vfcvt.rtz.xu.f`) encode the returning type mnemonics into their overloaded variant to help distinguish them.

The following shows how `_x`, `_rtz_x`, `_xu`, and `_rtz_xu` is appended to the suffix for distinction.

```c
vint32m1_t __riscv_vfcvt_x (vfloat32m1_t src, size_t vl);
vint32m1_t __riscv_vfcvt_rtz_x (vfloat32m1_t src, size_t vl);
vuint32m1_t __riscv_vfcvt_xu (vfloat32m1_t src, size_t vl);
vuint32m1_t __riscv_vfcvt_rtz_xu (vfloat32m1_t src, size_t vl);
```

==== `vreinterpret`, LMUL truncate/extension, and `vset`/`vget`

These pseudo intrinsics encode the return type (e.g. `__riscv_vreinterpret_b8`) into their overloaded variants to help distinguish them.

The following shows how the return type is appended to the suffix for distinction.

```c
vfloat32m1_t __riscv_vreinterpret_f32m1 (vint32m1_t src);
vuint32m1_t __riscv_vreinterpret_u32m1 (vint32m1_t src);
vint8m1_t __riscv_vreinterpret_i8m1 (vint32m1_t src);
vint16m1_t __riscv_vreinterpret_i16m1 (vint32m1_t src);
vint64m1_t __riscv_vreinterpret_i64m1 (vint32m1_t src);
vbool64_t __riscv_vreinterpret_b64 (vint32m1_t src);
vbool32_t __riscv_vreinterpret_b32 (vint32m1_t src);
vbool16_t __riscv_vreinterpret_b16 (vint32m1_t src);
vbool8_t __riscv_vreinterpret_b8 (vint32m1_t src);
vbool4_t __riscv_vreinterpret_b4 (vint32m1_t src);
```

[[unsupported-implicit-naming]]
=== Un-supported intrinsics for implicit (overloaded) naming scheme

Due to the limitation of the C language (without the aid of features like C++ templates), some intrinsics do not have an overloaded version. Intrinsics with characteristics of either of the following do not possess an overloaded version.

- Intrinsics with input arguments are all scalar types and scalar types alone (e.g. unmasked vector load instruction intrinsics, `vmv.s.x`)
- Intrinsics with `vl` as the only parameter (e.g. `vmclr`, `vmset`, `vid`)
- Intrinsics with vector boolean input(s), returning a vector non-boolean vector type (e.g. `viota`)

[[type-system]]
== Type system

The RVV intrinsics are designed to be strongly-typed. The intrinsics provide `vreinterpret` intrinsics to help users go across the strongly-typed scheme if necessary.

Non-mask (integer and floating-point) data types have SEW and LMUL encoded. 

[[integer-type]]
=== Integer types

The integer types have EEW and EMUL encoded into the type. The first row describes the EMUL and the first column describes the data type and element width of the scalar type.

Type with bold font is only available when `ELEN >= 64` (that is, unavailable under `Zve32*`).

.Integer types
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Types     | EMUL=1/8      | EMUL=1/4       | EMUL=1/ 2      | EMUL=1        | EMUL=2        | EMUL=4        | EMUL=8
| `int8_t`    | `*vint8mf8_t*`  | `vint8mf4_t`     | `vint8mf2_t`     | `vint8m1_t`     | `vint8m2_t`     | `vint8m4_t`     | `vint8m8_t`
| `int16_t`   | N/A           | `*vint16mf4_t*`  | `vint16mf2_t`    | `vint16m1_t`    | `vint16m2_t`    | `vint16m4_t`    | `vint16m16_t`
| `int32_t`   | N/A           | N/A            | `*vint32mf2_t*`  | `vint32m1_t`    | `vint32m2_t`    | `vint32m4_t`    | `vint32m32_t`
| `int64_t`   | N/A           | N/A            | N/A            | `*vint64m1_t*`  | `*vint64m2_t*`  | `*vint64m4_t*`  | `*vint64m8_t*`
| `uint8_t`   | `*vuint8mf8_t*` | `vuint8mf4_t`    | `vuint8mf2_t`    | `vuint8m1_t`    | `vuint8m2_t`    | `vuint8m4_t`    | `vuint8m8_t`
| `uint16_t`  | N/A           | `*vuint16mf4_t*` | `vuint16mf2_t`   | `vuint16m1_t`   | `vuint16m2_t`   | `vuint16m4_t`   | `vuint16m8_t`
| `uint32_t`  | N/A           | N/A            | `*vuint32mf2_t*` | `vuint32m1_t`   | `vuint32m2_t`   | `vuint32m4_t`   | `vuint32m8_t`
| `uint64_t`  | N/A           | N/A            | N/A            | `*vuint64m1_t*` | `*vuint64m2_t*` | `*vuint64m4_t*` | `*vuint64m8_t*`
|===

[[floating-point-type]]
=== Floating-point types

The floating-point types have EEW and EMUL encoded into the type. The first row describes the EMUL and the first column describes the data type and element width of the scalar type.

Floating-point types with element widths of 16 (Types=`float16_t`) requires the `zvfh` and `zvfhmin` extension to be specified in the architecture.

Floating-point types with element widths of 32 (Types=`float32_t`) requires the `zve32f` extension to be specified in the architecture.

Floating-point types with element widths of 64 (Types=`float64_t`) requires the `zve64d` extension to be specified in the architecture.

.Floating-point types
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Types      | EMUL=1/8 | EMUL=1/4   | EMUL=1/ 2   | EMUL=1     | EMUL=2     | EMUL=4   | EMUL=8
| `float16_t`  | N/A        | `vfloat16m4_t` | `vfloat16mf2_t` | `vfloat16m1_t` | `vfloat16m2_t` | `vfloat16m4_t` | `vfloat16m8_t`
| `float32_t`  | N/A        | N/A          | `vfloat32mf2_t` | `vfloat32m1_t` | `vfloat32m2_t` | `vfloat32m4_t` | `vfloat32m8_t`
| `float64_t`  | N/A        | N/A          | N/A           | `vfloat64m1_t` | `vfloat64m2_t` | `vfloat64m4_t` | `vfloat64m8_t`
|===

=== Mask types

The mask types encode the ratio that is derived from `EEW`/`EMUL`. The mask types represent mask register values that follows the Mask Register Layout ^14^.

.Mask types
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Types | n = 1    | n = 2    | n = 4    | n = 8    | n = 16    | n = 32    | n = 64
| `bool`  | `vbool1_t` | `vbool2_t` | `vbool4_t` | `vbool8_t` | `vbool16_t` | `vbool32_t` | `vbool64_t`
|===

=== Tuple type

The tuple types encode `SEW`, `LMUL`, and `NFIELD`^16^ into the data type.

These types are utilized for the segment load/store instruction intrinsics, the types listed in <<integer-type>> and <<floating-point-type>> all have tuple types. Types under the combination of `LMUL`, `NFIELD` follows the restriction by v-spec - EMUL * NFIELDS ≤ 8. 

Availability of the tuple types follows the availability of their corresponding non-tuple (`NFIELD=1`) types.

.Tuple types (EMUL=1/8)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1) | NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8mf8_t` | `vint8mf8x2_t` | `vint8mf8x3_t` | `vint8mf8x4_t` | `vint8mf8x5_t` | `vint8mf8x6_t` | `vint8mf8x7_t` | `vint8mf8x8_t`
| `vuint8mf8_t` | `vuint8mf8x2_t` | `vuint8mf8x3_t` | `vuint8mf8x4_t` | `vuint8mf8x5_t` | `vuint8mf8x6_t` | `vuint8mf8x7_t` | `vuint8mf8x8_t`
|===

.Tuple types (EMUL=1/4)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1)| NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8mf4_t` | `vint8mf4x2_t` | `vint8mf4x3_t` | `vint8mf4x4_t` | `vint8mf4x5_t` | `vint8mf4x6_t` | `vint8mf4x7_t` | `vint8mf4x8_t`
| `vuint8mf4_t` | `vuint8mf4x2_t` | `vuint8mf4x3_t` | `vuint8mf4x4_t` | `vuint8mf4x5_t` | `vuint8mf4x6_t` | `vuint8mf4x7_t` | `vuint8mf4x8_t`
| `vint16mf4_t` | `vint16mf4x2_t` | `vint16mf4x3_t` | `vint16mf4x4_t` | `vint16mf4x5_t` | `vint16mf4x6_t` | `vint16mf4x7_t` | `vint16mf4x8_t`
| `vuint16mf4_t` | `vuint16mf4x2_t` | `vuint16mf4x3_t` | `vuint16mf4x4_t` | `vuint16mf4x5_t` | `vuint16mf4x6_t` | `vuint16mf4x7_t` | `vuint16mf4x8_t`
| `vfloat16mf4_t` | `vfloat16mf4x2_t` | `vfloat16mf4x3_t` | `vfloat16mf4x4_t` | `vfloat16mf4x5_t` | `vfloat16mf4x6_t` | `vfloat16mf4x7_t` | `vfloat16mf4x8_t`
|===

.Tuple types (EMUL=1/2)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1) | NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8mf2_t` | `vint8mf2x2_t` | `vint8mf2x3_t` | `vint8mf2x4_t` | `vint8mf2x5_t` | `vint8mf2x6_t` | `vint8mf2x7_t` | `vint8mf2x8_t`
| `vuint8mf2_t` | `vuint8mf2x2_t` | `vuint8mf2x3_t` | `vuint8mf2x4_t` | `vuint8mf2x5_t` | `vuint8mf2x6_t` | `vuint8mf2x7_t` | `vuint8mf2x8_t`
| `vint16mf2_t` | `vint16mf2x2_t` | `vint16mf2x3_t` | `vint16mf2x4_t` | `vint16mf2x5_t` | `vint16mf2x6_t` | `vint16mf2x7_t` | `vint16mf2x8_t`
| `vuint16mf2_t` | `vuint16mf2x2_t` | `vuint16mf2x3_t` | `vuint16mf2x4_t` | `vuint16mf2x5_t` | `vuint16mf2x6_t` | `vuint16mf2x7_t` | `vuint16mf2x8_t`
| `vint32mf2_t` | `vint32mf2x2_t` | `vint32mf2x3_t` | `vint32mf2x4_t` | `vint32mf2x5_t` | `vint32mf2x6_t` | `vint32mf2x7_t` | `vint32mf2x8_t`
| `vuint32mf2_t` | `vuint32mf2x2_t` | `vuint32mf2x3_t` | `vuint32mf2x4_t` | `vuint32mf2x5_t` | `vuint32mf2x6_t` | `vuint32mf2x7_t` | `vuint32mf2x8_t`
| `vfloat16mf2_t` | `vfloat16mf2x2_t` | `vfloat16mf2x3_t` | `vfloat16mf2x4_t` | `vfloat16mf2x5_t` | `vfloat16mf2x6_t` | `vfloat16mf2x7_t` | `vfloat16mf2x8_t`
| `vfloat32mf2_t` | `vfloat32mf2x2_t` | `vfloat32mf2x3_t` | `vfloat32mf2x4_t` | `vfloat32mf2x5_t` | `vfloat32mf2x6_t` | `vfloat32mf2x7_t` | `vfloat32mf2x8_t`
|===

.Tuple types (EMUL=1)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1) | NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8m1_t` | `vint8m1x2_t` | `vint8m1x3_t` | `vint8m1x4_t` | `vint8m1x5_t` | `vint8m1x6_t` | `vint8m1x7_t` | `vint8m1x8_t`
| `vuint8m1_t` | `vuint8m1x2_t` | `vuint8m1x3_t` | `vuint8m1x4_t` | `vuint8m1x5_t` | `vuint8m1x6_t` | `vuint8m1x7_t` | `vuint8m1x8_t`
| `vint16m1_t` | `vint16m1x2_t` | `vint16m1x3_t` | `vint16m1x4_t` | `vint16m1x5_t` | `vint16m1x6_t` | `vint16m1x7_t` | `vint16m1x8_t`
| `vuint16m1_t` | `vuint16m1x2_t` | `vuint16m1x3_t` | `vuint16m1x4_t` | `vuint16m1x5_t` | `vuint16m1x6_t` | `vuint16m1x7_t` | `vuint16m1x8_t`
| `vint32m1_t` | `vint32m1x2_t` | `vint32m1x3_t` | `vint32m1x4_t` | `vint32m1x5_t` | `vint32m1x6_t` | `vint32m1x7_t` | `vint32m1x8_t`
| `vuint32m1_t` | `vuint32m1x2_t` | `vuint32m1x3_t` | `vuint32m1x4_t` | `vuint32m1x5_t` | `vuint32m1x6_t` | `vuint32m1x7_t` | `vuint32m1x8_t`
| `vint64m1_t` | `vint64m1x2_t` | `vint64m1x3_t` | `vint64m1x4_t` | `vint64m1x5_t` | `vint64m1x6_t` | `vint64m1x7_t` | `vint64m1x8_t`
| `vuint64m1_t` | `vuint64m1x2_t` | `vuint64m1x3_t` | `vuint64m1x4_t` | `vuint64m1x5_t` | `vuint64m1x6_t` | `vuint64m1x7_t` | `vuint64m1x8_t`
| `vfloat16m1_t` | `vfloat16m1x2_t` | `vfloat16m1x3_t` | `vfloat16m1x4_t` | `vfloat16m1x5_t` | `vfloat16m1x6_t` | `vfloat16m1x7_t` | `vfloat16m1x8_t`
| `vfloat32m1_t` | `vfloat32m1x2_t` | `vfloat32m1x3_t` | `vfloat32m1x4_t` | `vfloat32m1x5_t` | `vfloat32m1x6_t` | `vfloat32m1x7_t` | `vfloat32m1x8_t`
| `vfloat64m1_t` | `vfloat64m1x2_t` | `vfloat64m1x3_t` | `vfloat64m1x4_t` | `vfloat64m1x5_t` | `vfloat64m1x6_t` | `vfloat64m1x7_t` | `vfloat64m1x8_t`
|===

.Tuple types (EMUL=2)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1) | NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8m2_t` | `vint8m2x2_t` | `vint8m2x3_t` | `vint8m2x4_t` | N/A | N/A | N/A | N/A
| `vuint8m2_t` | `vuint8m2x2_t` | `vuint8m2x3_t` | `vuint8m2x4_t` | N/A | N/A | N/A | N/A
| `vint16m2_t` | `vint16m2x2_t` | `vint16m2x3_t` | `vint16m2x4_t` | N/A | N/A | N/A | N/A
| `vuint16m2_t` | `vuint16m2x2_t` | `vuint16m2x3_t` | `vuint16m2x4_t` | N/A | N/A | N/A | N/A
| `vint32m2_t` | `vint32m2x2_t` | `vint32m2x3_t` | `vint32m2x4_t` | N/A | N/A | N/A | N/A
| `vuint32m2_t` | `vuint32m2x2_t` | `vuint32m2x3_t` | `vuint32m2x4_t` | N/A | N/A | N/A | N/A
| `vint64m2_t` | `vint64m2x2_t` | `vint64m2x3_t` | `vint64m2x4_t` | N/A | N/A | N/A | N/A
| `vuint64m2_t` | `vuint64m2x2_t` | `vuint64m2x3_t` | `vuint64m2x4_t` | N/A | N/A | N/A | N/A
| `vfloat16m2_t` | `vfloat16m2x2_t` | `vfloat16m2x3_t` | `vfloat16m2x4_t` | N/A | N/A | N/A | N/A
| `vfloat32m2_t` | `vfloat32m2x2_t` | `vfloat32m2x3_t` | `vfloat32m2x4_t` | N/A | N/A | N/A | N/A
| `vfloat64m2_t` | `vfloat64m2x2_t` | `vfloat64m2x3_t` | `vfloat64m2x4_t` | N/A | N/A | N/A | N/A
|===

.Tuple types (EMUL=4)
[cols="2,2,2,2,2,2,2,2"]
[%autowidth]
|===
| Non-tuple Types (NFILED=1) | NFIELD=2   | NFIELD=3    | NFIELD=4     | NFIELD=5     | NFIELD=6   | NFIELD=7 | NFIELD=8
| `vint8m4_t` | `vint8m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vuint8m4_t` | `vuint8m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vint16m4_t` | `vint16m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vuint16m4_t` | `vuint16m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vint32m4_t` | `vint32m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vuint32m4_t` | `vuint32m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vint64m4_t` | `vint64m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vuint64m4_t` | `vuint64m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vfloat16m4_t` | `vfloat16m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vfloat32m4_t` | `vfloat32m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
| `vfloat64m4_t` | `vfloat64m4x2_t` | N/A | N/A | N/A | N/A | N/A | N/A
|===


[[pseudo-intrinsics]]
== Pseudo intrinsics

The intrinsics provide extra utility functions to help users manipulate across the RVV intrinsic types. These functions are called "pseudo intrinsics". These pseudo intrinsics do not represent any real instructions.

[[pseudo-vsetvl-vsetvlmax]]
=== `vsetvl`/`vsetvlmax`

[[pseudo-vreinterpret]]
=== `vreinterpret`

[[pseudo-vundefined]]
=== `vundefined`

[[pseudo-vget-vset]]
=== `vget`/`vset`

[[pseudo-vlmul_trunc-vlmul_ext]]
=== `vlmul_trunc`/`vlmul_ext`

== Programming Notes

=== The `vd` parameters in the intrinsics

Intrinsics whose computation is relevant to value held in `vd` have a passthrough operand in them. The following list enumerates the intrinsics that has a passthrough operand. Please see the appendix for the exact prototypes of these intrinsics.

- Intrinsics with tail-undisturbed (`vta=0`)
- Intrinsics with mask-undisturbed (`vma=0`)
- Intrinsics representing Vector Multiply-Add Operations ^13^
- Intrinsics representing Vector Slideup Instructions ^24^

For intrinsics with no `vd` operand, the compiler is free to pick any register as the destination register.

=== Assumption of `vstart=0` for intrinsics users.

The `vstart` CSR is currently not exposed to the intrinsics programmer, and the intrinsics have the semantics of `vstart = 0`. Support for positive `vstart` values is implementation defined, thus portable application software should not set `vstart > 0`.

=== Assembly generated from the intrinsics

Some users may expect the intrinsics to directly translate and appear in the assembly, the intrinsics are the interfaces that expose the vector instruction semantics. The compiler is free to optimize them out if there is an opportunity.

=== Bookkeeping of configurations in the compiler

Control to `vl`, `vtype`, `vxrm`, and `frm` is directly exposed to the user. The compiler is responsible to set the correct value into these CSR-s to perform the expected semantic of the intrinsic functions.

=== Strided load/store with stride of 0

The v-spec mentions ^15^ that the strided load/store instruction with stride of 0 could have different behaviors to perform all memory accesses or fewer memory operations. Since needing all memory accesses isn't likely to be common, the compiler implementation is allowed to generate fewer memory operations with strided load/store intrinsics.

In other words, the compiler does not guarantee generating the all memory accesses instruction in strided load/store intrinsics with stride of 0. If the user needs all memory accesses to be performed, they should use an indexed load/store intrinsics with all zero indices.

=== Leveraging instructions with operand mnemonics of `vi`

The RVV intrinsics provides intrinsics with operand mnemonics of `vv` and `vx` but not `vi`. This was an intentional design to reduce the total amount of out-going intrinsics. The compiler is responsible to emit instructions with operand mnemonics of `vi` when an immediate that can be expressed within 5-bit is provided to the intrinsics.

== References

^0^https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc[Github - riscv/riscv-v-spec/v-spec.adoc]

^1^https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md[Github - riscv-non-isa/riscv-c-api-doc/riscv-c-api.md]

^2^https://llvm.org/docs/RISCVUsage.html[User Guide for RISC-V Target]

^3^https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html[RISC-V Options (Using the GNU Compiler Collection (GCC))]

^4^ Section 3.4.1 (Vector selected element width `vsew[2:0]`) in v-spec ^0^

^5^ Section 3.4.2 (Vector Register Grouping (`vlmul[2:0]``)) in v-spec ^0^

^6^ Section 3.4.3 (Vector Tail Agnostic and Vector Mask Agnostic `vta` and `vma`) in v-spec ^0^

^7^ Section 5.3 (Vector Masking) in v-spec ^0^

^8^ Section 3.8 (Vector Fixed-Point Rounding Mode Register `vxrm`) in v-spec ^0^

^9^ https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/master/riscv-cc.adoc#vector-register-convention[psABI: Vector Register Convention]

^10^ https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf[The RISC-V Instruction Set Manual: 8.2 Floating-Point Control and Status Register]

^11^ Section 3.5 (Vector Length Register) in v-spec ^0^

^12^ Section 3.4.2 in v-spec ^0^

^13^ Section 11.13, 11.14, 13.6, 13.7 in v-spec ^0^

^14^ Section 4.5 (Mask Register Layout) in v-spec ^0^

^15^ Section 7.5 in v-spec ^0^

^16^ Section 7.8 in v-spec ^0^

^17^ Section 5.2 (Vector Operands) in v-spec ^0^

^18^ Section 6 (Configuration-Setting Instructions) in v-spec ^0^

^19^ Section 18 (Standrad Vector Extensions) in v-spec ^0^

^20^ Section 18.2 (Zve*: Vector Extensions for Embedded Processors) in v-spec ^0^

^21^ Section 12 (Vector Fixed-Point Arithmetic Instructions) in v-spec ^0^

^22^ Section 3.9 (3.9. Vector Fixed-Point Saturation Flag vxsat) in v-spec ^0^

^23^ Section 13 (Vector Floating-Point Instructions) in v-spec ^0^

^24^ Section 16.3.1 (Vector Slideup Instructions) in v-spec ^0^

^25^ Section 3.7 (Vector Start Index CSR `vstart`) in v-spec ^0^
